//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKütüphaneOtomasyonu.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCEZALAR
    {
        public int ID { get; set; }
        public Nullable<int> UYE { get; set; }
        public string BASLANGİCTARİHİ { get; set; }
        public string BİTİSTARİHİ { get; set; }
        public Nullable<int> PARA { get; set; }
        public string HAREKET { get; set; }
    }
}
